### ISSUE TITLE
Support of compressed n5 datasets

### ISSUE THREAD

**Issue by unidesigner** [aschampion/h2n5#3]
The [z5](https://github.com/constantinpape/z5) library supports a number of compression codecs when creating an n5 array. Are some of them already supported or is the plan to do so? Thanks.

**Comment by aschampion** [comment]
Yes, compression is supported. h2n5 uses the n5 crate's default feature flags, which [include support for the same default compression codecs as Java N5](https://github.com/aschampion/rust-n5/blob/master/Cargo.toml#L13): bzip, gzip, lz4, and xz.

z5 additionally supports blosc, which would be trivial to add to rust n5 since [rust bindings](https://github.com/asomers/blosc-rs) exist.
